/**
 * DATOS SIMULADOS DEL MARKETPLACE
 * Tiendas, productos y reseñas de ejemplo para Nicaragua
 */

import type { Store, Product, Review } from "./types-negocios"

// ==========================================
// TIENDAS DE EJEMPLO
// ==========================================

export const MOCK_STORES: Store[] = [
  {
    id: "1",
    nombre: "TecnoShop Managua",
    slug: "tecnoshop-managua",
    categoria: "Tecnología",
    departamento: "Managua",
    direccion: "Metrocentro, 2do piso, módulo 245",
    coordenadas: { lat: 12.1364, lng: -86.2514 },
    telefono: "+505 2222-3333",
    whatsapp: "+505 8888-9999",
    email: "info@tecnoshop.com.ni",
    descripcion:
      "La mejor tienda de tecnología en Nicaragua. Vendemos smartphones, laptops, accesorios y más. Garantía en todos nuestros productos.",
    avatar: "/tech-store-logo-blue.jpg",
    banner: "/modern-tech-store.png",
    rating: 4.5,
    totalReviews: 234,
    estado: "activo",
    horarios: [
      { dia: "Lunes", apertura: "09:00", cierre: "18:00" },
      { dia: "Martes", apertura: "09:00", cierre: "18:00" },
      { dia: "Miércoles", apertura: "09:00", cierre: "18:00" },
      { dia: "Jueves", apertura: "09:00", cierre: "18:00" },
      { dia: "Viernes", apertura: "09:00", cierre: "18:00" },
      { dia: "Sábado", apertura: "10:00", cierre: "16:00" },
      { dia: "Domingo", apertura: "00:00", cierre: "00:00", cerrado: true },
    ],
    delivery: { habilitado: true, costoBase: 50, radioKm: 15 },
    facturacion: true,
    retiroEnTienda: true,
    productosActivos: 156,
    ventasTotales: 2340,
    clientes: 890,
    fechaCreacion: "2021-03-15",
    verificada: true,
    nueva: false,
  },
  {
    id: "2",
    nombre: "Sabores de Nicaragua",
    slug: "sabores-nicaragua",
    categoria: "Comida",
    departamento: "Granada",
    direccion: "Calle La Calzada, frente al Parque Central",
    coordenadas: { lat: 11.9344, lng: -85.956 },
    telefono: "+505 2552-1234",
    whatsapp: "+505 7777-8888",
    descripcion:
      "Restaurante de comida típica nicaragüense. Nacatamales, vigorón, indio viejo y más. Ambiente familiar.",
    avatar: "/nicaraguan-food-restaurant-logo.jpg",
    banner: "/traditional-nicaraguan-food-dishes.jpg",
    rating: 4.8,
    totalReviews: 512,
    estado: "activo",
    horarios: [
      { dia: "Lunes", apertura: "07:00", cierre: "21:00" },
      { dia: "Martes", apertura: "07:00", cierre: "21:00" },
      { dia: "Miércoles", apertura: "07:00", cierre: "21:00" },
      { dia: "Jueves", apertura: "07:00", cierre: "21:00" },
      { dia: "Viernes", apertura: "07:00", cierre: "22:00" },
      { dia: "Sábado", apertura: "07:00", cierre: "22:00" },
      { dia: "Domingo", apertura: "08:00", cierre: "20:00" },
    ],
    delivery: { habilitado: true, costoBase: 30, radioKm: 8 },
    facturacion: true,
    retiroEnTienda: true,
    productosActivos: 45,
    ventasTotales: 8900,
    clientes: 2100,
    fechaCreacion: "2019-06-20",
    verificada: true,
  },
  {
    id: "3",
    nombre: "Moda Urbana León",
    slug: "moda-urbana-leon",
    categoria: "Ropa",
    departamento: "León",
    direccion: "Centro Comercial Plaza León, Local 15",
    coordenadas: { lat: 12.4379, lng: -86.8779 },
    telefono: "+505 2311-5678",
    whatsapp: "+505 8765-4321",
    descripcion:
      "Ropa de moda para jóvenes. Las últimas tendencias a precios accesibles. Marcas nacionales e importadas.",
    avatar: "/fashion-clothing-store-logo.jpg",
    banner: "/modern-clothing-display.png",
    rating: 4.2,
    totalReviews: 178,
    estado: "activo",
    horarios: [
      { dia: "Lunes", apertura: "10:00", cierre: "19:00" },
      { dia: "Martes", apertura: "10:00", cierre: "19:00" },
      { dia: "Miércoles", apertura: "10:00", cierre: "19:00" },
      { dia: "Jueves", apertura: "10:00", cierre: "19:00" },
      { dia: "Viernes", apertura: "10:00", cierre: "20:00" },
      { dia: "Sábado", apertura: "10:00", cierre: "20:00" },
      { dia: "Domingo", apertura: "11:00", cierre: "17:00" },
    ],
    delivery: { habilitado: false },
    facturacion: true,
    retiroEnTienda: true,
    productosActivos: 234,
    ventasTotales: 1560,
    clientes: 678,
    fechaCreacion: "2022-01-10",
    verificada: false,
    nueva: true,
  },
  {
    id: "4",
    nombre: "Casa & Decoración",
    slug: "casa-decoracion",
    categoria: "Hogar",
    departamento: "Managua",
    direccion: "Galerías Santo Domingo, 1er nivel",
    coordenadas: { lat: 12.115, lng: -86.27 },
    telefono: "+505 2278-9012",
    email: "ventas@casadeco.ni",
    descripcion:
      "Todo para tu hogar. Muebles, decoración, electrodomésticos y artículos de cocina. Calidad garantizada.",
    avatar: "/home-decor-furniture-store-logo.jpg",
    banner: "/modern-home-interior-showroom.jpg",
    rating: 4.6,
    totalReviews: 89,
    estado: "activo",
    horarios: [
      { dia: "Lunes", apertura: "10:00", cierre: "20:00" },
      { dia: "Martes", apertura: "10:00", cierre: "20:00" },
      { dia: "Miércoles", apertura: "10:00", cierre: "20:00" },
      { dia: "Jueves", apertura: "10:00", cierre: "20:00" },
      { dia: "Viernes", apertura: "10:00", cierre: "21:00" },
      { dia: "Sábado", apertura: "10:00", cierre: "21:00" },
      { dia: "Domingo", apertura: "11:00", cierre: "19:00" },
    ],
    delivery: { habilitado: true, costoBase: 100, radioKm: 20 },
    facturacion: true,
    retiroEnTienda: true,
    productosActivos: 312,
    ventasTotales: 456,
    clientes: 234,
    fechaCreacion: "2020-09-05",
    verificada: true,
  },
  {
    id: "5",
    nombre: "Deportes Total",
    slug: "deportes-total",
    categoria: "Deportes",
    departamento: "Masaya",
    direccion: "Mercado Municipal, módulo 78",
    coordenadas: { lat: 11.9742, lng: -86.0942 },
    telefono: "+505 2522-3456",
    whatsapp: "+505 8234-5678",
    descripcion:
      "Artículos deportivos para todas las disciplinas. Uniformes, equipos, calzado y accesorios. ¡Ponte en forma!",
    avatar: "/sports-equipment-store-logo.jpg",
    banner: "/sports-equipment-store-display.jpg",
    rating: 4.3,
    totalReviews: 145,
    estado: "activo",
    horarios: [
      { dia: "Lunes", apertura: "08:00", cierre: "18:00" },
      { dia: "Martes", apertura: "08:00", cierre: "18:00" },
      { dia: "Miércoles", apertura: "08:00", cierre: "18:00" },
      { dia: "Jueves", apertura: "08:00", cierre: "18:00" },
      { dia: "Viernes", apertura: "08:00", cierre: "18:00" },
      { dia: "Sábado", apertura: "08:00", cierre: "17:00" },
      { dia: "Domingo", apertura: "00:00", cierre: "00:00", cerrado: true },
    ],
    delivery: { habilitado: true, costoBase: 40, radioKm: 10 },
    facturacion: false,
    retiroEnTienda: true,
    productosActivos: 189,
    ventasTotales: 2100,
    clientes: 567,
    fechaCreacion: "2018-04-12",
    verificada: true,
  },
  {
    id: "6",
    nombre: "ElectroMundo",
    slug: "electromundo",
    categoria: "Tecnología",
    departamento: "Chinandega",
    direccion: "Avenida Central, contiguo a Banpro",
    coordenadas: { lat: 12.6294, lng: -87.0311 },
    telefono: "+505 2341-7890",
    descripcion: "Electrónica y electrodomésticos. Televisores, audio, computadoras y más. Financiamiento disponible.",
    avatar: "/electronics-store-logo.png",
    rating: 3.9,
    totalReviews: 67,
    estado: "cerrado_temporal",
    horarios: [
      { dia: "Lunes", apertura: "09:00", cierre: "17:00" },
      { dia: "Martes", apertura: "09:00", cierre: "17:00" },
      { dia: "Miércoles", apertura: "09:00", cierre: "17:00" },
      { dia: "Jueves", apertura: "09:00", cierre: "17:00" },
      { dia: "Viernes", apertura: "09:00", cierre: "17:00" },
      { dia: "Sábado", apertura: "09:00", cierre: "14:00" },
      { dia: "Domingo", apertura: "00:00", cierre: "00:00", cerrado: true },
    ],
    delivery: { habilitado: false },
    facturacion: true,
    retiroEnTienda: true,
    productosActivos: 78,
    ventasTotales: 890,
    clientes: 345,
    fechaCreacion: "2017-11-20",
    verificada: false,
  },
  {
    id: "7",
    nombre: "Pizzería Don Mario",
    slug: "pizzeria-don-mario",
    categoria: "Comida",
    departamento: "Managua",
    direccion: "Carretera Masaya Km 5.5",
    coordenadas: { lat: 12.1, lng: -86.23 },
    telefono: "+505 2270-1234",
    whatsapp: "+505 8111-2222",
    descripcion: "Las mejores pizzas artesanales de Managua. Ingredientes frescos y masa hecha al momento.",
    avatar: "/pizza-restaurant-logo-italian.jpg",
    banner: "/artisan-pizza-restaurant-interior.jpg",
    rating: 4.7,
    totalReviews: 423,
    estado: "activo",
    horarios: [
      { dia: "Lunes", apertura: "11:00", cierre: "22:00" },
      { dia: "Martes", apertura: "11:00", cierre: "22:00" },
      { dia: "Miércoles", apertura: "11:00", cierre: "22:00" },
      { dia: "Jueves", apertura: "11:00", cierre: "22:00" },
      { dia: "Viernes", apertura: "11:00", cierre: "23:00" },
      { dia: "Sábado", apertura: "11:00", cierre: "23:00" },
      { dia: "Domingo", apertura: "12:00", cierre: "21:00" },
    ],
    delivery: { habilitado: true, costoBase: 35, radioKm: 12 },
    facturacion: true,
    retiroEnTienda: true,
    productosActivos: 32,
    ventasTotales: 12500,
    clientes: 3200,
    fechaCreacion: "2015-08-10",
    verificada: true,
  },
  {
    id: "8",
    nombre: "Fit Zone Gym Store",
    slug: "fit-zone-gym-store",
    categoria: "Deportes",
    departamento: "Managua",
    direccion: "Plaza Inter, nivel 2",
    coordenadas: { lat: 12.12, lng: -86.26 },
    telefono: "+505 2266-7890",
    descripcion: "Suplementos deportivos, ropa fitness y equipos de entrenamiento. Asesoría nutricional incluida.",
    avatar: "/gym-fitness-store-logo.jpg",
    rating: 4.4,
    totalReviews: 98,
    estado: "activo",
    horarios: [
      { dia: "Lunes", apertura: "07:00", cierre: "21:00" },
      { dia: "Martes", apertura: "07:00", cierre: "21:00" },
      { dia: "Miércoles", apertura: "07:00", cierre: "21:00" },
      { dia: "Jueves", apertura: "07:00", cierre: "21:00" },
      { dia: "Viernes", apertura: "07:00", cierre: "21:00" },
      { dia: "Sábado", apertura: "08:00", cierre: "18:00" },
      { dia: "Domingo", apertura: "09:00", cierre: "15:00" },
    ],
    delivery: { habilitado: true, costoBase: 45, radioKm: 15 },
    facturacion: true,
    retiroEnTienda: true,
    productosActivos: 145,
    ventasTotales: 780,
    clientes: 289,
    fechaCreacion: "2023-02-14",
    verificada: true,
    nueva: true,
  },
]

// ==========================================
// PRODUCTOS DE EJEMPLO
// ==========================================

export const MOCK_PRODUCTS: Product[] = [
  // Productos de TecnoShop Managua
  {
    id: "p1",
    storeId: "1",
    nombre: "iPhone 15 Pro 256GB",
    descripcion: "El iPhone más avanzado. Chip A17 Pro, cámara de 48MP y titanio.",
    precio: 18500,
    precioAnterior: 19500,
    categoria: "Celulares",
    imagenes: ["/iphone-15-pro-titanium.png"],
    estado: "activo",
    rating: 4.9,
    totalReviews: 45,
    stock: 12,
    destacado: true,
  },
  {
    id: "p2",
    storeId: "1",
    nombre: "MacBook Air M3",
    descripcion: 'Laptop ultraligera con chip M3. Pantalla Liquid Retina de 13.6".',
    precio: 24900,
    categoria: "Laptops",
    imagenes: ["/macbook-air-m3-silver.jpg"],
    estado: "activo",
    rating: 4.8,
    totalReviews: 28,
    stock: 8,
  },
  {
    id: "p3",
    storeId: "1",
    nombre: "AirPods Pro 2da Gen",
    descripcion: "Cancelación activa de ruido, audio espacial y estuche con USB-C.",
    precio: 4500,
    precioAnterior: 4990,
    categoria: "Accesorios",
    imagenes: ["/airpods-pro-2-white.jpg"],
    estado: "activo",
    rating: 4.7,
    totalReviews: 89,
    stock: 25,
  },
  {
    id: "p4",
    storeId: "1",
    nombre: "Samsung Galaxy S24 Ultra",
    descripcion: "El Galaxy más potente. S Pen incluido, cámara de 200MP.",
    precio: 22500,
    categoria: "Celulares",
    imagenes: ["/samsung-galaxy-s24-ultra-black.jpg"],
    estado: "agotado",
    rating: 4.6,
    totalReviews: 34,
    stock: 0,
  },
  // Productos de Sabores de Nicaragua
  {
    id: "p5",
    storeId: "2",
    nombre: "Nacatamal Tradicional",
    descripcion: "Nacatamal hecho con receta familiar. Incluye cerdo, arroz y vegetales.",
    precio: 120,
    categoria: "Platos Típicos",
    imagenes: ["/nicaraguan-nacatamal-traditional.jpg"],
    estado: "activo",
    rating: 4.9,
    totalReviews: 156,
    stock: 50,
    destacado: true,
  },
  {
    id: "p6",
    storeId: "2",
    nombre: "Vigorón Completo",
    descripcion: "Yuca con chicharrón y ensalada de repollo. Porción generosa.",
    precio: 85,
    categoria: "Platos Típicos",
    imagenes: ["/nicaraguan-vigoron-dish.jpg"],
    estado: "activo",
    rating: 4.8,
    totalReviews: 203,
    stock: 100,
  },
  {
    id: "p7",
    storeId: "2",
    nombre: "Indio Viejo",
    descripcion: "Tradicional indio viejo con tortilla. Sabor auténtico.",
    precio: 95,
    categoria: "Platos Típicos",
    imagenes: ["/nicaraguan-indio-viejo-dish.jpg"],
    estado: "activo",
    rating: 4.7,
    totalReviews: 89,
    stock: 30,
  },
  // Productos de Moda Urbana León
  {
    id: "p8",
    storeId: "3",
    nombre: "Jeans Slim Fit Azul",
    descripcion: "Jeans de mezclilla premium. Corte slim, tallas 28-38.",
    precio: 650,
    precioAnterior: 890,
    categoria: "Pantalones",
    imagenes: ["/blue-slim-fit-jeans-denim.jpg"],
    estado: "activo",
    rating: 4.3,
    totalReviews: 45,
    stock: 35,
  },
  {
    id: "p9",
    storeId: "3",
    nombre: "Camiseta Básica Pack x3",
    descripcion: "Pack de 3 camisetas básicas. Algodón 100%. Negro, blanco y gris.",
    precio: 450,
    categoria: "Camisetas",
    imagenes: ["/placeholder.svg?height=400&width=400"],
    estado: "activo",
    rating: 4.5,
    totalReviews: 78,
    stock: 60,
    destacado: true,
  },
  // Productos de Casa & Decoración
  {
    id: "p10",
    storeId: "4",
    nombre: "Sofá Modular 3 Piezas",
    descripcion: "Sofá modular en tela gris. Cómodo y elegante.",
    precio: 12500,
    categoria: "Muebles",
    imagenes: ["/placeholder.svg?height=400&width=400"],
    estado: "activo",
    rating: 4.6,
    totalReviews: 23,
    stock: 5,
    destacado: true,
  },
  {
    id: "p11",
    storeId: "4",
    nombre: "Lámpara de Pie Industrial",
    descripcion: "Lámpara estilo industrial. Altura ajustable, bombilla incluida.",
    precio: 1890,
    categoria: "Iluminación",
    imagenes: ["/placeholder.svg?height=400&width=400"],
    estado: "activo",
    rating: 4.4,
    totalReviews: 34,
    stock: 18,
  },
  // Productos de Deportes Total
  {
    id: "p12",
    storeId: "5",
    nombre: "Balón Fútbol Profesional",
    descripcion: "Balón oficial tamaño 5. Costuras reforzadas.",
    precio: 450,
    categoria: "Fútbol",
    imagenes: ["/placeholder.svg?height=400&width=400"],
    estado: "activo",
    rating: 4.5,
    totalReviews: 67,
    stock: 40,
  },
  {
    id: "p13",
    storeId: "5",
    nombre: "Tenis Running Nike",
    descripcion: "Zapatillas para correr. Amortiguación Air Max.",
    precio: 2200,
    precioAnterior: 2800,
    categoria: "Calzado",
    imagenes: ["/placeholder.svg?height=400&width=400"],
    estado: "activo",
    rating: 4.7,
    totalReviews: 89,
    stock: 20,
    destacado: true,
  },
  // Productos de Pizzería Don Mario
  {
    id: "p14",
    storeId: "7",
    nombre: "Pizza Suprema Grande",
    descripcion: "Pizza con pepperoni, jamón, champiñones, pimiento y cebolla.",
    precio: 320,
    categoria: "Pizzas",
    imagenes: ["/placeholder.svg?height=400&width=400"],
    estado: "activo",
    rating: 4.8,
    totalReviews: 234,
    stock: 999,
    destacado: true,
  },
  {
    id: "p15",
    storeId: "7",
    nombre: "Calzone de Jamón",
    descripcion: "Calzone relleno de jamón, queso mozzarella y ricotta.",
    precio: 180,
    categoria: "Calzones",
    imagenes: ["/placeholder.svg?height=400&width=400"],
    estado: "activo",
    rating: 4.6,
    totalReviews: 89,
    stock: 999,
  },
  // Productos de Fit Zone
  {
    id: "p16",
    storeId: "8",
    nombre: "Proteína Whey 2kg",
    descripcion: "Proteína de suero de leche. 25g proteína por porción.",
    precio: 890,
    categoria: "Suplementos",
    imagenes: ["/placeholder.svg?height=400&width=400"],
    estado: "activo",
    rating: 4.5,
    totalReviews: 56,
    stock: 30,
    destacado: true,
  },
  {
    id: "p17",
    storeId: "8",
    nombre: "Mancuernas Ajustables 20kg",
    descripcion: "Par de mancuernas ajustables. De 2.5kg a 20kg cada una.",
    precio: 3500,
    categoria: "Equipos",
    imagenes: ["/placeholder.svg?height=400&width=400"],
    estado: "agotado",
    rating: 4.8,
    totalReviews: 23,
    stock: 0,
  },
]

// ==========================================
// RESEÑAS DE EJEMPLO
// ==========================================

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    storeId: "1",
    userId: "u1",
    userName: "Carlos Mendoza",
    userAvatar: "/placeholder.svg?height=50&width=50",
    rating: 5,
    comentario:
      "Excelente servicio y productos originales. Compré un iPhone y la garantía funcionó perfectamente cuando tuve un problema menor.",
    fecha: "2024-01-15",
    respuesta: {
      texto: "¡Gracias Carlos! Nos alegra que hayas tenido una buena experiencia.",
      fecha: "2024-01-16",
    },
  },
  {
    id: "r2",
    storeId: "1",
    userId: "u2",
    userName: "María López",
    userAvatar: "/placeholder.svg?height=50&width=50",
    rating: 4,
    comentario: "Buenos precios y variedad. El único detalle es que a veces tardan en atender cuando hay mucha gente.",
    fecha: "2024-01-10",
  },
  {
    id: "r3",
    storeId: "2",
    userId: "u3",
    userName: "Roberto García",
    userAvatar: "/placeholder.svg?height=50&width=50",
    rating: 5,
    comentario: "El mejor vigorón que he probado en mi vida. Porciones generosas y sabor auténtico. 100% recomendado.",
    fecha: "2024-01-18",
  },
  {
    id: "r4",
    storeId: "2",
    userId: "u4",
    userName: "Ana Martínez",
    userAvatar: "/placeholder.svg?height=50&width=50",
    rating: 5,
    comentario: "Los nacatamales son espectaculares. El servicio es muy amable y el lugar está muy limpio.",
    fecha: "2024-01-12",
  },
  {
    id: "r5",
    storeId: "3",
    userId: "u5",
    userName: "Diego Hernández",
    userAvatar: "/placeholder.svg?height=50&width=50",
    rating: 4,
    comentario: "Buena ropa a buen precio. Me gustaría que tuvieran más variedad de tallas grandes.",
    fecha: "2024-01-20",
  },
  {
    id: "r6",
    storeId: "7",
    userId: "u6",
    userName: "Laura Sánchez",
    userAvatar: "/placeholder.svg?height=50&width=50",
    rating: 5,
    comentario: "Las mejores pizzas de Managua, sin duda. La masa es perfecta y los ingredientes frescos.",
    fecha: "2024-01-22",
    respuesta: {
      texto: "¡Muchas gracias Laura! Te esperamos pronto.",
      fecha: "2024-01-22",
    },
  },
]

// ==========================================
// FUNCIONES DE UTILIDAD
// ==========================================

/** Obtiene productos por ID de tienda */
export function getProductsByStoreId(storeId: string): Product[] {
  return MOCK_PRODUCTS.filter((p) => p.storeId === storeId)
}

/** Obtiene reseñas por ID de tienda */
export function getReviewsByStoreId(storeId: string): Review[] {
  return MOCK_REVIEWS.filter((r) => r.storeId === storeId)
}

/** Obtiene una tienda por su ID */
export function getStoreById(storeId: string): Store | undefined {
  return MOCK_STORES.find((s) => s.id === storeId)
}
